java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    RESTART_APP: 1
    CAMUNDA_URL: "https://camunda-${SERVICE_FQDN}/engine-rest/"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    POSTGRES_NAME: wa_workflow_api
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_USERNAME: hmcts
    POSTGRES_PASSWORD: ${GENERIC_HMCTS_YAML_PASS}
    POSTGRES_CONNECTION_OPTIONS: ""
    DB_READER_USERNAME: "postgres"
  keyVaults:
    wa:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: s2s-secret-workflow-api
          alias: S2S_SECRET_WORKFLOW_API

  postgresql:
    releaseNameOverride: "{{ .Release.Name }}-postgresql"
    enabled: true
    ingressHost: "postgres-{{ .Release.Name }}.preview.platform.hmcts.net"
    image:
      registry: hmctsprod.azurecr.io
      repository: imported/bitnami/postgresql
      tag: '11.6.0'
    auth:
      username: hmcts
      password: ${GENERIC_HMCTS_YAML_PASS}
      postgresPassword: ${GENERIC_HMCTS_YAML_PASS}
    primary:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 25m
      initdb:
        scripts:
          init.sql: |
            ALTER ROLE hmcts SUPERUSER;
            CREATE DATABASE "wa_workflow_api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
            CREATE DATABASE "camunda" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;

wa:
  enabled: true
  wa:
    taskManagement:
      enabled: true
    taskMonitor:
      enabled: false
    eventHandler:
      enabled: false
    workflow:
      enabled: false
    taskBatchCron:
      enabled: true
    messageCron:
      enabled: true
    servicebus:
      enabled: false
    postgresql:
      enabled: false
    camunda:
      enabled: false
    reconfigurationBatchCron:
      enabled: false
    terminationBatchCron:
      enabled: false

camunda-bpm:
  enabled: true
  java:
    releaseNameOverride: "{{ .Release.Name }}-camunda"
    ingressHost: "camunda-{{ .Release.Name }}.preview.platform.hmcts.net"
    disableKeyVaults: true
    environment:
      CAMUNDA_DB_HOST: "{{ .Release.Name }}-postgresql"
      CAMUNDA_DB_USER_NAME: hmcts
      CAMUNDA_DB_PASSWORD: ${GENERIC_HMCTS_YAML_PASS}
      CAMUNDA_DB_CONN_OPTIONS: ""
      CAMUNDA_DB_NAME: camunda
      TASK_MANAGEMENT_API_URL: http://{{ .Release.Name }}-wa-task-management-api
      CAMUNDA_BPM_DATABASE_SCHEMAUPDATE: true
      RELEASE_REVISION: "{{ .Release.Revision }}"
      CAMUNDA_API_AUTH_ENABLED: false

wa-message-cron-service:
  job:
    schedule: "*/1 * * * *"
    releaseNameOverride: "{{ .Release.Name }}-wa-message-cron"

  wa-initiation-batch:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-wa-task-batch"

  wa-reconfiguration-batch:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-reconfiguration"

  wa-termination-batch:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-termination-batch"

  wa-task-management-api:
    java:
      disableKeyVaults: true
      ingressHost: wa-task-management-api-${SERVICE_FQDN}
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        CAMUNDA_URL: "http://{{ .Release.Name }}-camunda/engine-rest"
        IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
        S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
        ROLE_ASSIGNMENT_URL: http://${SERVICE_NAME}-am-role-assignment-service
        ALLOWED_JURISDICTIONS: wa,divorce
        ALLOWED_CASE_TYPES: financialremedymvp2,financialremedycontested
        LAUNCH_DARKLY_SDK_KEY: ${WA_LAUNCH_DARKLY_SDK_KEY}
        MANDATORY_TASK_FIELD_CHECK_ENABLED: false
        CCD_DATA_STORE_URL: http://${SERVICE_NAME}-ccd-data-store-api
        S2S_SECRET_TASK_MANAGEMENT_API: ${S2S_SECRET_TASK_MANAGEMENT_API}
        WA_IDAM_CLIENT_SECRET: ${WA_IDAM_CLIENT_SECRET}
        WA_SYSTEM_PASSWORD: ${WA_SYSTEM_PASSWORD}
        WA_SYSTEM_USERNAME: ${WA_SYSTEM_USERNAME}
